### ISSUE TITLE
Remove global wildcards from .gitignore

### ISSUE THREAD

**Issue by SteffRhes** [acdh-oeaw/apis-ontologies#38]
In .gitignore there are some global wildcards like so:
```
*cache*
*foo*
*local*
*temp*
```

This need to be removed or adapted to be more precise, as it can be the case that files containing a matching substring would get ignored (as just happened to me with a migration on `TempEntityClass`).

Best to do over all repos.

**Comment by koeaw** [comment]
Unassigning myself as I think exclusion of certain words merits consideration.

The general idea is to prevent accidental adding of files which oughtn't be committed to a shared repo, either because they are assumed to contain local settings or to exist only temporarily. Following on from that, actual project files shouldn't include these words in their file names to reduce ambiguity. This general idea aside, our `README` currently contains instructions for creating a file for local settings and any such file in use locally would be affected by removal of the ignore rule for `*local*`.

-> I'm freeing this ticket up so the removal (which itself is easy) can be picked up by anyone who thinks otherwise.

**Comment by b1rger** [comment]
Closing this issue, as the repository is being phased out
