### ISSUE TITLE
Improve entity-specific settings

### ISSUE THREAD

**Issue by steffres** [acdh-oeaw/apis-ontologies#9]
In vanilla, settings for entities (e.g. how filter fields are arranged) are defined in the settings file. I suggest to attach them directly to their model classes in the apis-ontology as they relate more to the classes than to the settings file and also they can be compared at a glance (e.g. verifying that filter fields relate to existing attribute fields).

**Comment by steffres** [comment]
> removal of any code that assumes these configs can be found in a settings file.

Exactly. 

And any need for restructuring will arise along this task.

**Comment by koeaw** [comment]
I feel like this should be moved to [acdh-oeaw/apis-core-rdf](https://github.com/acdh-oeaw/apis-core-rdf) (where I was just looking for this issue) because it only affects this repository in terms of documentation and perhaps examples in `base_project`.

It should probably also be reworded for clarification because as discussed above, the subject line is currently misleading re: what the actual issue is/what needs doing.

**Comment by koeaw** [comment]
Ohh, hum, looks like you did originally create an issue in the other repo :thinking: -> acdh-oeaw/apis-core-rdf/issues/9

**Comment by steffres** [comment]
Yeah, I should have mentioned in the other issue that I was closing it so that I could recreate it here.

As for the discussion about it belonging to this repo or the other: I don't have a strong preference and see good reason for either. Since this issue is already being discussed and the other one is close, I will leave it here.

As for clarifications, well, it means that *everything* for which the dictionary [APIS_ENTITIES](https://github.com/acdh-oeaw/apis-devops/blob/49abaf4ec17fa9771bd10fc7ed4929a952917f40/apis/settings/base.py#L452) in apis vanilla was used, should be moved to the respective classes. Simple as that.

**Comment by koeaw** [comment]
Suggestion:  
Rewrite handling of entity-specific settings to work on the principle of _exclusion_ rather than inclusion.

Reasoning:  
The assumption is most if not all fields of an entity should be accessible/visible in the various views anyway (except perhaps for table views). For the few fields for which this really isn't the case, it would make much more sense to specifically add them to an exlusion list.

---

The way `entity_settings` works right now is really cumbersome and error-prone:  
Whenever new fields are added to an entity / existing fields are removed / existing fields are renamed, all `entity_settings` keys need to be reviewed and modified manually. The more fields an entity has, the more of a hassle this process becomes (the lists with field names get harder to parse visually + require more frequent reformatting).

We also currently cannot exclude any of the default fields for models from appearing in the various views, we can only change the order in which fields are displayed. The only exception to this are table views, which only have the `name` default field added to them.

-> For any view other than table views, all default fields are displayed before any user-provided ones, meaning we have to provide a list of field names in `entity_settings` if we want user-provided fields to show up first (often just repeating the order in which they appear in the model...). Tables are created solely based on the values in `table_fields` (field names are converted to table columns) _except_ that the `name` default field always gets auto-appended as last column if it is not already included in `table_fields`.

--- 

Ways in which an exclusion-based approach would be advantageous:
* reduces redundancy
* easier maintenance of `entity_settings` dictionaries in models
* allows exclusion of default fields for individual views

Maybe table views would need to be treated differently either way, idk. (But e.g. `additional_cols` could simply be calculated by subtracting table fields from all available fields.)

Field order might also need some more thinking about. I'd suggest to simply use the order in which fields are included in the model for user-specific fields but maybe with `name` prepended, so e.g.:  
`name` (unless excluded) + custom fields (minus excluded) + remaining default fields (minus excluded), but there might be a need for ordering fields differently depending on the view.

`id` is currently not included with the default fields at all, not sure if this is done on purpose and if there are more fields we already filter out anyway, so this would also require more thinking about (I currently use `id` in one table as workaround for sorting by "last added", for example).

**Comment by koeaw** [comment]
> We also currently cannot exclude any of the default fields for models from appearing in the various views, we can only change the order in which fields are displayed. 

Actually, this is also true for custom fields... There is no way to e.g. include all in `form_order` but exclude some from `list_filters`. If only some custom fields are added to `list_filters`, those will display first in an entity's list view, followed by all default fields, followed by all other custom fields.

**Comment by sennierer** [comment]
I agree with @koeaw regarding the exclusion. Apart from the table views (due to too many columns) we should have exclusion rather than inclusion.

I am also not very happy with the settings of the views being moved in the models.py file.
Imho we should have a separation of concerns in ORM (all the orm/database logic should go in models.py) and views/appearance, all of that should go in the settings.

If I recall correctly the rational behind moving it in the models.py was that back then we did not have the settings in the ontology and thus it made sense to keep it with the project, but now it doesnt make sense anymore I think.
@steffres any strong opinions for keeping the view based settings (table columns, filters, form order) with the ORM models rather than with the app settings?

**Comment by koeaw** [comment]
I don't know if the settings file is the best solution, either.

IMO it's not intuitive to go looking for model-specific settings in the file that's meant/used for _overall_ app settings (it took me way too long to discover that particular dict in vanilla APIS settings files) and I personally also prefer that there's not one large data structure that holds the settings for all individual models.

The advantage of keeping the settings close to the models is a reduction in potential errors/misconfigurations & time spent debugging. Problems I've encountered with the old way of doing things so far: 
1) Settings aren't picked up due to mismatches in model names and labels (due to typos or failure to _manually update_ labels after model class renames),
 2) brand new models have "random" settings applied to them out of nowhere due to old/unused/leftover settings with matching names (happened to me because I'd copy/pasted parts of the dict from elsewhere much earlier just to figure out the various config options... again, took an unncessary amount of time to track down).

**Comment by koeaw** [comment]
Btw. the reason you have to add `settings.APIS_ENTITIES` back in now is because I intentionally started dropping it in my PRs at some point due to this ticket. 

See e.g. acdh-oeaw/apis-core-rdf#20, which has been merged into `dev` but may not yet be present on `main` (nevermind it seems to need additional work):

> As before, references to settings.APIS_ENTITIES were dropped altogether; entity settings are assumed to be set for each entity class individually in models.py going forward (see discussion in https://github.com/acdh-oeaw/apis-ontologies/issues/9).

**Comment by koeaw** [comment]
Having thought about this some more, I think two things would help with the problems I pointed out (and make me less opposed to moving the settings back to the settings file):

* proper, detailed documentation of how to configure entity settings in our README (+ example settings in `base_project`, see also open PR #7), i.e. where to put the settings, a _complete_ list of options and explanation of what they are used for
* some sort of check that makes devs aware there's a mismatch between available model fields and settings currently defined for a model, the results of which could e.g. be output as warnings in templates when `DEV_VERSION` is set to `True`

I'll also say that I don't think `APIS_ENTITIES` is a great variable name. It may work in the context of the settings file itself, but should be more explicit about what it's for (which is data returned or _displayed_ on the frontend, and nothing to do with the entities, i.e. the models, themselves).

**Comment by steffres** [comment]
I agree with most, and personally have no strong opinion either way.

However I think that an automatic check for fields being in sync would be overengineering. Especially since we have a brutish kind of check already: Django would break if something is wrong. ;P

**Comment by b1rger** [comment]
Just to summarize what we are talking about (as documented in https://acdh-oeaw.github.io/apis-core/_build/html/configuration.html#apis-entities):
```
        "merge": True,
        "search": ["name"],
        "form_order": ["name", "kind", "lat", "lng", "status", "collection"],
        "table_fields": ["name"],
        "additional_cols": ["id", "lat", "lng", "part_of"],
        "list_filters": [
            {"name": {"method": "name_label_filter"}},
            {"collection": {"label": "Collection"}},
            {"kind": {"label": "Kind of Place"}},
            "related_entity_name",
            "related_relationtype_name",
            "lat",
            "lng",
        ],
```
The `APIS_ENTITIES` setting appears in in https://github.com/acdh-oeaw/apis-core-rdf/blob/be7616470f0a0d7b021c86c7757db2a879298ab4/apis_core/apis_entities/filters.py#L155, but it is commented out, so has no effect. 

In https://github.com/acdh-oeaw/apis-core-rdf/blob/be7616470f0a0d7b021c86c7757db2a879298ab4/apis_core/apis_entities/autocomplete3.py it occurs two times, both times accessing the `search` key.

In https://github.com/acdh-oeaw/apis-core-rdf/blob/be7616470f0a0d7b021c86c7757db2a879298ab4/apis_core/apis_entities/views.py#L186 it accesses the `table_fields` key. 

In https://github.com/acdh-oeaw/apis-core-rdf/blob/be7616470f0a0d7b021c86c7757db2a879298ab4/apis_core/apis_entities/models.py#L692 it is used to get a list of all the defined entities, but the method containing the code is commented with: `I don't remember what this function was used for.`. The same method is also part of the `models.py` in `apis_metainfo`, but commented out.

In https://github.com/acdh-oeaw/apis-core-rdf/blob/be7616470f0a0d7b021c86c7757db2a879298ab4/apis_core/apis_entities/forms.py#L172 it is accessed to get the key `form_order`.

I agree with @sennierer  that those settings should be part of the models, given that they are all about UI.

What I think is important, is that the settings should come with sensible defaults - it should not be necessary to define an `APIS_ENTITIES` dict anywhere. The `TempEntityClass` could provide a `@property` method that simply returns a list of sensible default fields. This method should allow some kind of include/exclude list.

**Comment by steffres** [comment]
> I agree with @sennierer that those settings should be part of the models, given that they are all about UI.

Didn't you yesterday say that the settings should *not* be part of the models?

Overall, yes, these settings are heavily utilized throughout the code base. Thanks for the context.

Again, while I don't have a preference where they are stored I'm strongly of the opinion to decide on one place only and not aim for supporting two places.

**Comment by b1rger** [comment]
> > I agree with @sennierer that those settings should be part of the models, given that they are all about UI.
> 
> Didn't you yesterday say that the settings should _not_ be part of the models?

Ah, yeah, sorry, I dropped an important `not` ;) fixed now

**Comment by koeaw** [comment]
> However I think that an automatic check for fields being in sync would be overengineering. Especially since we have a brutish kind of check already: Django would break if something is wrong. ;P

The thing is though, Django does not always "break" in helpful / consistent / easily detectable ways when there's something wrong with those fields – and it shouldn't, IMO, since these settings aren't about base functionality but basically frontend helpers.

Filters, for example, fail in non-obvious ways when an unknown field name is provided, because the code that loops through the fields is incomplete (the error says the wrong variable type was provided when that's not true). And you won't know about it until you try to access _the one entity_ for which the field name is incorrect. I think it would make much more sense to have filters skip faulty fields and print out a message to devs instead to check their field names (and those faulty fields should be caught properly anyway).

**Comment by steffres** [comment]
Fair enough.

**Comment by steffres** [comment]
Just pointing to one relevant part of code which will be affected by this issue: https://github.com/acdh-oeaw/apis-core-rdf/blob/eb0d4bc80635d55e9ba7aa000ff614a0759c0f3a/apis_core/apis_entities/models.py#L966

**Comment by koeaw** [comment]
Since we've more or less decided to switch back to using `APIS_ENTITIES` in `server_settings.py` (and are almost done with that, AFAIK) and this issue was mostly used to discuss the pros and cons, I feel it could be closed now.

I'd like to keep my suggestion to rewrite the settings to work based on exclusion around but think it would make more sense to create a new follow-up issue just for that.
